version: '3'
services:
    client:
        build:
            context: .
            dockerfile: Dockerfile.client
        ports:
            - "3001:3000"
            - "35729:35729"
        volumes:
            - ./packages/client:/app/packages/client
        links:
            - db
    server:
        build:
            context: .
            dockerfile: Dockerfile.server
        command: yarn --cwd packages/server dev
        ports:
            - "8000:8000"
        volumes:
            - ./packages/server:/app/packages/server
        links:
            - db
        environment:
          MONGODB_URI: mongodb://db:27017/gobygame
    db:
        image: mongo
        ports:
          - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: gobygame
